### ISSUE TITLE
pywin32 issue(s) under Python 3.6.1

### ISSUE THREAD

**Issue by xoviat** [mhammond/pywin32#748]
It appears that changes in Python 3.6.1 have broken at least one feature in pywin32 220. I suspect that specifically it is this: https://bugs.python.org/issue29100

While arguably a maintenance release of Python should not be introducing such breaking changes - and so a ticket should also be raised there - it looks like perhaps this has just exposed an existing issue in pywin32, where previously the relevant Python API was more permissive. 

Here is an example of the problem:

~~~
> import getpass, sspi, sspicon, win32security
> client_name = getpass.getuser()
> auth_info = (client_name, 'wherever.com', None)
> pkg_info = win32security.QuerySecurityPackageInfo('Kerberos')
> win32security.AcquireCredentialsHandle(
>     client_name, pkg_info['Name'],
>     sspicon.SECPKG_CRED_OUTBOUND,
>     None, auth_info)                             
                                                                            
ValueError: year 30828 is out of range
~~~

I think that `AcquireCredentialsHandle()` is returning a 'never expires' timestamp, which is out of the range of Python's `datetime`. Perhaps this case should be represented as `datetime.max`?

Reported by: m-parry

Original Ticket: [pywin32/bugs/748](https://sourceforge.net/p/pywin32/bugs/748)

**Comment by berseus** [comment]
This breaks requests-negotiate-sspi as well: https://github.com/brandond/requests-negotiate-sspi/issues/12

**Comment by dhirschfeld** [comment]
As a user of `requests-negotiate-sspi` I'm affected by this so am just posting here so I get notified of any updates...

**Comment by dhirschfeld** [comment]
I just saw a comment stating that a new release was imminent so I'm putting in a final plug for this issue in the hope that a fix makes it in to the new release!

**Comment by mhammond** [comment]
Should be fixed by #07202650

**Comment by mhammond** [comment]
hrm - github didn't link the above commit - let's try 07202650d21e8fa7f3053ff1d4665363315cefce :)

**Comment by dhirschfeld** [comment]
To automatically link (and close) this issue from the commit message you need to prefix the issue number with one of the [recognised keywords](https://help.github.com/articles/closing-issues-using-keywords/) - e.g.
```
Closes #748
Fixes #748
...etc...
```

**Comment by wenqiangwang** [comment]
It seems the issue is still there. 
I installed pywin32 222 and tried the following code:
```
import requests
from requests_negotiate_sspi import HttpNegotiateAuth
r = requests.get('https://xxx', auth=HttpNegotiateAuth())
```
Still got the following error:
```
  File "C:\Python\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range
```

**Comment by dhirschfeld** [comment]
That's strange since it definitely works for me.

Are you sure you're running the latest? You can find out programmatically, in the exact same python session where you got the exception just run the below commands:
```python
import win32api
fixed_file_info = win32api.GetFileVersionInfo(win32api.__file__, '\\')
fixed_file_info['FileVersionLS'] >> 16
```

**Comment by mhammond** [comment]
It's probably pywintypesxx.dll that matters here:

> >>> import pywintypes, win32api
> >>> fixed_file_info = win32api.GetFileVersionInfo(pywintypes.__file__, '\\')
> >>> fixed_file_info['FileVersionLS'] >> 16
> 222

**Comment by mhammond** [comment]
(*sob* - my markup foo is poor - `pywintypes.__file__`)

**Comment by wenqiangwang** [comment]
You are correct Mark. My win32api is 222 but pywintypes is 220. Do you know how to update it to 222?

```
>>> import win32api
>>> fixed_file_info = win32api.GetFileVersionInfo(win32api.__file__, '\\')
>>> fixed_file_info['FileVersionLS'] >> 16
222
```

```
>>> import pywintypes
>>> fixed_file_info = win32api.GetFileVersionInfo(pywintypes.__file__, '\\')
>>> fixed_file_info['FileVersionLS'] >> 16
220
```

**Comment by mhammond** [comment]
I suspect the correct version is in the lib\site-packages\pywin32_system32 directory, and for some reason the post-install script failed to copy it to the system32 (or SysWow64, depending on 64 vs 32 bit) directory.

Running `python Scripts\pywin32_postinstall.py -install` from an *elevated* command prompt should do the right thing.

**Comment by wenqiangwang** [comment]
Its the case. Mark. But I just wonder with pypiwin32 I don't need to run another except for 'pip install pypiwin32'. Is it possible to update the pypiwin32 module to 222 too?

**Comment by mhammond** [comment]
I think @xoviat just converted the existing installers. Best I can tell, wheel doesn't have any postinstall script support, although maybe I missed it.

**Comment by wenqiangwang** [comment]
It worked. Thank you!
